### ISSUE TITLE
Feedback for “Front Matter Reference”

### ISSUE THREAD

**Issue by loganwoolf** [bigcommerce/docs#79]
I'm having a difficult time understanding the difference between what comes after products and what comes after limit.
```
category:	
  shop_by_price: true   # displays shop by price controls
  products: 10          # displays 10 products per page for this category 
    limit:  10          # limits products per page for this category to 10
```
